# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Leonardo/Documents/Arquivos Leonardo/UnB/9 Semestre/Projeto de Circuitos Reconfiguraveis/PCR/Prova1/funcao_sensorial/funcao_sensorial.srcs/sources_1/ip/ROM_x_ul/ROM_x_ul.xci
# IP: The module: 'ROM_x_ul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leonardo/Documents/Arquivos Leonardo/UnB/9 Semestre/Projeto de Circuitos Reconfiguraveis/PCR/Prova1/funcao_sensorial/funcao_sensorial.srcs/sources_1/ip/ROM_x_ul/ROM_x_ul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_x_ul'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Leonardo/Documents/Arquivos Leonardo/UnB/9 Semestre/Projeto de Circuitos Reconfiguraveis/PCR/Prova1/funcao_sensorial/funcao_sensorial.srcs/sources_1/ip/ROM_x_ul/ROM_x_ul.xci
# IP: The module: 'ROM_x_ul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leonardo/Documents/Arquivos Leonardo/UnB/9 Semestre/Projeto de Circuitos Reconfiguraveis/PCR/Prova1/funcao_sensorial/funcao_sensorial.srcs/sources_1/ip/ROM_x_ul/ROM_x_ul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_x_ul'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
